models.py
# coding: utf-8
from sqlalchemy import Column, ForeignKey, Index, Integer, TIMESTAMP, text
from sqlalchemy.dialects.mysql import SET, TINYINT, VARCHAR, ENUM
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func

Base = declarative_base()
metadata = Base.metadata

class Word(Base):
    __tablename__ = 'words'
    __table_args__ = (
        Index('base', 'en', 'vi', unique=True),
    )

    id = Column(Integer, primary_key=True)
    en = Column(VARCHAR(255), nullable=False)
    vi = Column(VARCHAR(255), nullable=False)
    spelling = Column(VARCHAR(255))
    hidden_at = Column(TIMESTAMP)
    is_active = Column(TINYINT, nullable=False, server_default=text("'0'"))
    priority = Column(TINYINT, nullable=False, server_default=text("'1'"))
    tags = Column(SET('vowels', 'consonants', 'colors', 'numbers'))
    last_attempt_at = Column(TIMESTAMP)


class Attempt(Base):
    __tablename__ = 'attempts'

    id = Column(Integer, primary_key=True)
    word_id = Column(ForeignKey('words.id', ondelete='CASCADE',
                     onupdate='CASCADE'), nullable=False, index=True)
    is_correct = Column(ENUM('no', 'yes'), nullable=False)
    answered_at = Column(TIMESTAMP, default=func.current_timestamp())
    word = relationship('Word')

app.py
from flask import Flask, redirect, session, url_for, request
import os
import click
from models import Word
from routes import words, api, articles
from db import db

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv(
    'SQLALCHEMY_DATABASE_URI', "mysql://root:@127.0.0.1:3306/phrases")
app.secret_key = "AW3[-498WM239D84]"


def create_app():

    db.init_app(app)

    @app.route("/")
    def home():
        if request.args.get('tag'):
            session['tag'] = request.args.get('tag')
        if request.args.get('all'):
            del session['tag']
        query = db.session.query(Word).filter(
            Word.hidden_at.is_(None), Word.is_active == 1).order_by(Word.last_attempt_at)

        if session.get('tag'):
            query = query.filter(Word.tags.in_([session.get('tag')]))
        word = query.first()

        return redirect(url_for('words.word', word_id=word.id))
    
    @app.cli.command("recreate-db")
    def recreate_db():
        db.create_all()

    app.register_blueprint(words.bp)
    app.register_blueprint(api.bp)
    app.register_blueprint(articles.bp)

    return app


if __name__ == '__main__':
    app = create_app()
    app.run('0.0.0.0', '8080', debug=True)

routes/api.py
from flask import jsonify
from flask import Blueprint
from sqlalchemy import func
from db import db
from models import Word

bp = Blueprint('api', __name__, url_prefix='/api')


@bp.route("/words")
def words():
    result = []
    query = db.session.query(Word).order_by(func.length(Word.vi))

    for word in query.all():
        result.append(
            {
                "value": str(word.id),
                "name": word.en + f" - {word.vi}" if word.vi else ''
            }
        )
    return jsonify({"results": result, "success": True})

routes/articles.py
from flask import render_template
from flask import Blueprint
import markdown


bp = Blueprint('articles', __name__, url_prefix='/articles')


@bp.route("")
def index():
    articles = []
    with open("articles/contents.txt") as file:
        while line := file.readline():
            arr = line.split(',')
            articles.append((arr[0], arr[1]))

    return render_template("articles/index.html", articles=articles)


@bp.route("/<article_id>")
def article(article_id):

    article = ""

    with open(f"articles/{article_id}") as file:
        article = file.read()
    return render_template("articles/article.html", article=markdown.markdown(article))

routes/words/__init__.py
from datetime import datetime
from flask import redirect, render_template, request, Blueprint, url_for, session

from models import Word, Attempt

from ..words import word as word_bp
from db import db
bp = Blueprint('words', __name__, url_prefix='/words')


@bp.route("/create", methods=['POST', 'GET'])
def create():
    if request.method == "POST":
        form = request.form

        word = Word()
        word.en = form.get("en")
        word.spelling = form.get("spelling") or None
        word.vi = form.get("vi") or None
        word.tags = form.get("tags") or None

        db.session.add(word)
        try:
            db.session.commit()
        except:
            db.session.rollback()
            word = db.session.query(Word).filter(
                Word.en == word.en, Word.vi == word.vi).first()
            return redirect(url_for("words.word", word_id=word.id))

        return redirect(url_for("words.word", word_id=word.id))
    return render_template("words/form.html")


@bp.route("/<word_id>", methods=['POST', 'GET'])
def word(word_id):
    user_result = None
    form = request.form
    user_answer = form.get('user_answer')

    word = db.session.query(Word).filter(Word.id == word_id).first()

    # Handling User Response
    if user_answer:
        word.last_attempt_at = datetime.now()
        
        attempt = Attempt()
        attempt.word_id = word.id
        attempt.is_correct = 'yes' if word.vi == user_answer else 'no'

        db.session.add(attempt)        
        db.session.commit()
    return render_template("words/word.html", word=word, parents=[], children=[], user_answer=user_answer, user_result=user_result)


@bp.route("")
def index():
    if "favourites" not in session:
        session["favourites"] = []
    query = db.session.query(Word).filter(Word.hidden_at.is_(
        None)).order_by(Word.is_active.desc(), Word.en)
    
    if request.args.get("favourites") and session["favourites"]:
        query = query.filter(Word.id.in_(session["favourites"]))

    return render_template("words/index.html", words=query.all(), favourites=session['favourites'])


bp.register_blueprint(word_bp.bp)

templates/articles/article.html
{% extends 'layout.html' %}

{% block content %}

<p>&nbsp;</p>

{{ article|safe }}
{% endblock %}

templates/articles/index.html
{% extends 'layout.html' %}

{% block content %}

<table class="ui compact celled table">
    <thead>
        <tr>
            <th>Название</th>
        </tr>
    </thead>
    <tbody>
        {% for article in articles %}
        <tr>
            <td><a href="{{ url_for('articles.article', article_id=article[0]) }}">{{ article[1] }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/dialogs.html
{% extends 'layout.html' %}

{% block content %}

<table class="ui compact celled table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Описание</th>
        </tr>
    </thead>
    <tbody>
        {% for dialog in dialogs %}
        <tr>
            <td><a href="{{ url_for('dialog', dialog_id=dialog.id) }}">{{ dialog.id }}</a></td>
            <td>{{ dialog.description }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/form.html
<h1>{{ word.base }}</h1>

<form action="{{ url_for('answer') }}" method="post" autocomplete="off" class="ui form">
    <input type="hidden" name="word_id" value="{{ word.id }}">
    {% if result == "fail" %}
    <input type="hidden" name="second_attempt" value=1>

    {% endif %}
    <input name="user_answer" style="width: 100%; height: 36px;">
    <br /><br />
    <button type="submit" style="width: 100%; height: 36px;" class="ui teal button">Check</button>
</form>

templates/layout.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/semantic.min.css"
        integrity="sha512-n//BDM4vMPvyca4bJjZPDh7hlqsQ7hqbP9RH18GF2hTXBY5amBwM2501M0GPiwCU/v9Tor2m13GOTFjk00tkQA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <div class="main ui container">
        <div>&nbsp;</div>
        <div class="ui compact fixed menu">
            <a class="item" href="{{ url_for('home') }}"><i class="home icon"></i></a>
            {% if word and word.id %}
            <a class="item" href="{{ url_for('words.word', word_id=word.id) }}"><i class="redo icon"></i></a>
            <a class="item" href="{{ url_for('words.word.edit', word_id=word.id) }}"><i class="edit icon"></i></a>
            <a class="item" target="_blank" href="https://translate.google.ru/?sl=vi&tl=en&text={{ word.vi }}"><i
                    class="google icon"></i></a>
            {% endif %}
            <a class="item" href="{{ url_for('words.create') }}"><i class="plus icon"></i></a>
            <!-- <a class="item" href="{{ url_for('words.index') }}">Todays Words</a> -->
            <a class="item" href="{{ url_for('words.index') }}"><i class="list icon"></i></a>
            <div class="ui dropdown simple item">
                More
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a class="item" href="{{ url_for('home', all=1) }}"><i class="home icon"></i> All</a>
                    <a class="item" href="{{ url_for('home', tag='numbers') }}"><i class="file icon"></i> Numbers</a>
                    <a class="item" href="{{ url_for('home', tag='colors') }}"><i class="adjust icon"></i> Colors</a>
                    <a class="item" href="{{ url_for('words.index', favourites=1) }}"><i class="heart icon"></i> Favourites</a>
                    <a class="item" href="http://thai-alphabet.com/" target="_blank">Alphabet</a>
                    <a class="item" href="{{ url_for('articles.index') }}">Articles</a>
                </div>
            </div>
        </div>
        <div>&nbsp;</div>

        {% block content %}

        {% endblock %}

    </div>
</body>

</html>

templates/words.html
{% extends 'layout.html' %}

{% block content %}

<table class="ui compact celled table">
    <thead>
        <tr>
            <th>Слово</th>
            <th>th</th>
            <th>Fail</th>
            <th>Success</th>
            <th>Active</th>
            <th>Manage</th>
        </tr>
    </thead>
    <tbody>
        {% for word_id, word in words.items() %}
        <tr
            class="{% if word.is_active and word.success %}{% if word.success >= word.fail %}positive{% else %}negative{% endif %}{% endif %}">
            <td><a href="{{ url_for('answer', word_id=word_id) }}">{{ word.base }}</a></td>
            <td><span class="ui big text">{{ word.th }}</span></td>
            <td>{{ word.fail or 0 }}</td>
            <td>{{ word.success or 0 }}</td>
            <td>{{ word.is_active }}</td>
            <td>{% if word.is_active %}
                <a href="{{ url_for('deactivate', word_id=word_id)}}" class="ui tiny red button">deactivate</a>
                {% else %}
                <a href="{{ url_for('activate', word_id=word_id)}}" class="ui primary button">activate</a>
                {% endif %}
            </td>
        </tr>

        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/words/form.html
{% extends 'layout.html' %}

{% block content %}
<div>&nbsp;</div>

<form class="ui form"
    action="{% if word %}{{ url_for('words.word.edit', word_id=word.id) }}{% else %}{{ url_for('words.create') }}{% endif %}"
    method="post" autocomplete="off">
    <div class="required field">
        <label>EN</label>
        <input type="text" name="en" value="{% if word %}{{ word.en }}{% endif %}" required>
    </div>
    <div class="field">
        <label>vi</label>
        <input type="text" name="vi" value="{% if word %}{{ word.vi or '' }}{% endif %}" autofocus>
    </div>
    <div class="field">
        <label>Priority</label>
        <input type="text" name="priority" value="{% if word %}{{ word.priority or 1 }}{% endif %}">
    </div>
    <div class="field">
        <label>Spelling</label>
        <textarea name="spelling">{% if word %}{{ word.spelling or '' }}{% endif %}</textarea>
    </div>
    <button class="ui teal button" type="submit">Save</button>
    <div class="field">
        <label>Tags</label>
        <select name="tags" multiple>
            <option value=""></option>
            {% for tag in ['vowels', 'consonants', 'colors', 'numbers'] %}
            <option value="{{ tag }}" {% if word and word.tags and tag in word.tags %} selected{% endif %}>{{ tag }}
            </option>
            {% endfor %}
        </select>
    </div>
    <button class="ui teal button" type="submit">Save</button>
</form>
{% endblock %}

templates/words/index.html
{% extends 'layout.html' %}

{% block content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/semantic.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/components/dropdown.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/components/dropdown.min.css">

<script>
    $(document).ready(function () {

        $('.words_dropdown').dropdown({
            clearable: true,
            fullTextSearch: true,
            filterRemoteData: true,
            onChange: function (value) {
                window.location.replace("/words/" + value);
            },
            apiSettings: {
                url: '/api/words?q={query}',
                cache: false
            }
        });

    });
</script>
<div>&nbsp;</div>
<div>
    <select class="ui fluid search words_dropdown">
    </select>

</div>


<table class="ui compact celled table">
    <thead>
        <tr>
            <th>Слово</th>
            <th>vi</th>
            <th>Translation</th>
            <th>Tags</th>
            <th>Manage</th>
        </tr>
    </thead>
    <tbody>
        {% for word in words %}
        <tr>
            <td><a href="{{ url_for('words.word', word_id=word.id) }}">{{ word.en }}</a></td>
            <td><span class="ui big text">{{ word.vi }}</span></td>
            <td><a target="_blank" href="https://translate.google.ru/?sl=th&tl=en&text={{ word.vi }}"><i
                        class="google icon"></i></a></td>
            <td>{{ word.tags or '' }}</td>
            <td>{% if word.is_active %}
                <a href="{{ url_for('words.word.deactivate', word_id=word.id)}}"
                    class="ui tiny red button">deactivate</a>
                {% else %}
                <a href="{{ url_for('words.word.activate', word_id=word.id)}}" class="ui primary button">activate</a>
                {% endif %}
            </td>
        </tr>

        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/words/word.html
{% extends 'layout.html' %}

{% block content %}


<h1>{{ word.en }}</h1>
{% if user_answer %}
<p><span class="ui big text">{{ word.vi }}</span></p>
<p><span class="ui big {% if word.vi == user_answer %}green{% else %}red{% endif %} text">{{ user_answer }}</span></p>
{% endif %}

{% if not user_answer or word.vi != user_answer %}
<form action="{{ url_for('words.word', word_id=word.id) }}" method="post" autocomplete="off" class="ui form">
    {% if result == "fail" %}
    <input type="hidden" name="second_attempt" value=1>

    {% endif %}
    <input name="user_answer" style="width: 100%; height: 36px;" required>
    <br /><br />
    <button type="submit" style="width: 100%; height: 36px;" class="ui teal button">Check</button>
</form>
{% endif %}

{% if user_result == "success" %}
<p><a href="{{ url_for('words.word.never', word_id=word.id) }}" class="ui red button">Never</a></p>
{% endif %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/semantic.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/components/dropdown.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/components/dropdown.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/components/accordion.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.2/components/accordion.min.css">
<script>
    $(document).ready(function () {

        $('.words_dropdown').dropdown({
            clearable: true,
            fullTextSearch: true,
            filterRemoteData: true,
            apiSettings: {
                url: '/api/words?q={query}',
                cache: false
            }
        });

        $('.ui.accordion').accordion()
    });
</script>

<div>&nbsp;</div>

<div class="ui styled accordion">
    <div class="title">
        <i class="dropdown icon"></i>Ответ
    </div>
    <div class="content">
        <p><span class="ui big text">{{ word.vi }}{% if word.spelling %} [{{ word.spelling }}]{% endif %}</span></p>
    </div>
    {% if children %}
    <div class="title">
        <i class="dropdown icon"></i>Входящие слова
    </div>
    <div class="content">
        <p>
        <table class="ui celled table">
            {% for el in children %}
            <tr>
                <td><a href="{{ url_for('words.word', word_id=el.id) }}">{{ el.en }}</a></td>
                <td>{{ el.vi }}</td>
            </tr>
            {% endfor %}
        </table>
        </p>
    </div>
    {% endif %}
    {% if parents %}
    <div class="title">
        <i class="dropdown icon"></i>Где используется
    </div>
    <div class="content">
        <p>
        <table class="ui celled table">
            {% for el in parents %}
            <tr>
                <td><a href="{{ url_for('words.word', word_id=el.id) }}">{{ el.en }}</a></td>
                <td>{{ el.vi }}</td>
            </tr>
            {% endfor %}
        </table>
        </p>
    </div>
    {% endif %}


    {% if word.comment %}
    <div class="title">
        <i class="dropdown icon"></i>Комментарий
    </div>
    <div class="content">
        <p>
            {{ word.comment }}
        </p>
    </div>
    {% endif %}
</div>

<div>&nbsp;</div>

<td>{% if word.is_active %}
    <a href="{{ url_for('words.word.deactivate', word_id=word.id)}}" class="ui tiny red button">deactivate</a>
    {% else %}
    <a href="{{ url_for('words.word.activate', word_id=word.id)}}" class="ui primary button">activate</a>
    {% endif %}
</td>


{% endblock %}